ManejoPresupuestos/Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuestos.Models;
using ManejoPresupuestos.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Runtime.CompilerServices;
//using Microsoft.Data.SqlClient;

namespace ManejoPresupuestos.Controllers
{
    public class TiposCuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServiciosUsuarios serviciosUsuarios;

        //private readonly string connectionString;
        //public TiposCuentasController(IConfiguration configuration)
        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServiciosUsuarios serviciosUsuarios)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.serviciosUsuarios = serviciosUsuarios;

            //connectionString = configuration.GetConnectionString("DefaultConnection");

        }

        public async Task<IActionResult> Index() 
        {
            var idUsuario = serviciosUsuarios.ObtenerUsuarioId();

            var tipoCuenta = await repositorioTiposCuentas.ObtenerTipoCuentaPorIdUsuario(idUsuario);  

            return View(tipoCuenta);
        }
        public IActionResult Crear()
        {
            //using (var connection = new SqlConnection(connectionString)) {
            //    var query = connection.Query("SELECT 1").FirstOrDefault();
            //}
                return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta) 
        {
            if(!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioId= serviciosUsuarios.ObtenerUsuarioId();

            var yaExisteTipoCuenta = 
                await repositorioTiposCuentas.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);

            if (yaExisteTipoCuenta) 
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre),
                                    $"El nombre {tipoCuenta.Nombre} ya existe.");
                return View(tipoCuenta);
            }
            await repositorioTiposCuentas.Crear(tipoCuenta);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre, int id) 
        {
            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();
            var existe = await repositorioTiposCuentas.Existe(nombre, usuarioId, id);

            if (existe) {
                return Json($"El nombre {nombre} ya existe");
            }

            return Json(true);

        }

        [HttpGet]
        public async Task<ActionResult> Editar(int id) {

            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId( id, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta); 
        }

        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuenta tipoCuenta) 
        {
            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();
            var existe = await repositorioTiposCuentas.ObtenerPorId(tipoCuenta.Id, usuarioId);

            if (existe is null) 
            {
                return RedirectToAction("NoEncontrado", "Home");

            }
            await repositorioTiposCuentas.Actualizar(tipoCuenta);
            
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<ActionResult> Borrar(int id) 
        {
            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);

            if (tipoCuenta == null) {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }

        [HttpPost]
        public async Task<ActionResult> BorrarTipoCuenta(int id) 
        {
            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioTiposCuentas.Borrar(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Ordenar([FromBody] int[] ids) 
        {
            var usuarioId = serviciosUsuarios.ObtenerUsuarioId();

            var tiposCuentas = await repositorioTiposCuentas.ObtenerTipoCuentaPorIdUsuario(usuarioId);

            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);

            var idsTiposCuentasNoPertenecenAlUsuario = ids.Except(idsTiposCuentas).ToList();

            if (idsTiposCuentasNoPertenecenAlUsuario.Count > 0) 
            {
                return Forbid();
            }

            var tiposCuentasOrdenadas = ids.Select((valor, indice) =>
            new TipoCuenta() { Id = valor, Orden = indice + 1 }).AsEnumerable();
            //  });
            await repositorioTiposCuentas.Ordenar(tiposCuentasOrdenadas);
            return Ok();
        }

    }
}

ManejoPresupuestos/Views/TiposCuentas/Borrar.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Borrado de tipo cuenta";
}

<h3 class="mb-3"> ¿Está seguro de que quiere eliminar el tipo de cuenta @Model.Nombre</h3>

<form asp-action="BorrarTipoCuenta">
    <input  type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

ManejoPresupuestos/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta


@{
    ViewData["Title"] = "Crear Tipo cuenta";
}


<h1> Crear Tipo de Cuenta</h1>
<h5> El tipo de cuenta se refiere a como podemos agrupar cunetas 
    Ejemplos: Préstamos, tarjetas de crédito, etc.</h5>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <form asp-controller="TiposCuentas" asp-action="Crear">
    
        <div class="mb-3">
            <label asp-for="Nombre" class="form-label">  </label>
            <input  asp-for="Nombre" class="form-control"/>
            <span asp-validation-for="Nombre" class="text-danger"></span>
            
        </div>

       @* <div class="mb-3">
            <label asp-for="Email" class="form-label"></label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"/>
        </div>

        <div asp-for="mb-3">
            <label asp-for="Edad" class="form-label"></label>
            <input asp-for="Edad" class="form-control" />
            <span asp-validation-for="Edad" class="text-danger"/>
        </div>

        <div asp-for="mb-3">
            <label asp-for="URL" class="form-label"></label>
            <input asp-for="URL" class="form-control"/>
            <span asp-validation-for="URL" class="text-danger"/>
        </div>
        
        <div class="mb-3">
            <label asp-for="TarjetaDeCredito" class="form-label"></label>
            <input asp-for="TarjetaDeCredito" class="form-control" />
            <span asp-validation-for="TarjetaDeCredito" class="text-danger" />
        </div>*@


        <button type="submit" class="btn btn-primary"> Enviar </button>
        <a class="btn btn-secondary" asp-action="Index"> Cancelar </a>
    
    </form>



@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

ManejoPresupuestos/Views/TiposCuentas/Editar.cshtml
@model TipoCuenta

@{
    ViewData["Title"] = "Editar Tipo Cuenta";
}

<h1> Editar Tipo Cuenta: @Model.Nombre</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-controller="TiposCuentas" asp-action="Editar">
    <input type="hidden" asp-for="Id"/>
    <div class="mb-3">

        <label asp-for="Nombre" class="form-label">  </label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>

    </div>

       <button type="submit" class="btn btn-primary"> Enviar </button>
    <a class="btn btn-secondary" asp-action="Index"> Cancelar </a>

</form>

ManejoPresupuestos/Views/TiposCuentas/Index.cshtml
@model IEnumerable<TipoCuenta> 


@{
    ViewData["Title"] = "Tipos cuentas";
}

<h1> Tipos de cuentas </h1>
<h5>El tipo de cuenta se refiere a cómo podemos agrupar cuentas.
    Ejemplos:  Préstamos, tarjetas de crédito , etc.
</h5>

<a asp-action="Crear" class="btn btn-primary mb-3"> Crear un nuevo tipo de cuenta</a>
@if(Model is not null)
{
    <table class="table table-bordered">
    
        <thead>
            <tr>
                <th>Acciones</th>
                <th>Nombre</th>
            </tr>
        </thead>
        <tbody id="reordenable">

        @foreach (var tipocuenta in Model)
        {
            <tr>
                <td>
                        <input type="hidden" value="@tipocuenta.Id" class="ids">
                        <a class="btn btn-primary" asp-controller="TiposCuentas"
                            asp-action="Editar" asp-route-id="@tipocuenta.Id">Editar</a>
                        <a class="btn btn-danger" asp-controller="TiposCuentas" 
                            asp-action="Borrar" asp-route-id="@tipocuenta.Id">Borrar</a>
                </td>
                <td>
                        @tipocuenta.Nombre
                </td>

            </tr>
        }
        </tbody>
    </table>
}

@section Scripts{
    <script>
        const urlOrdenar = '@Url.Action("ordenar")';
        $(function(){
            $("#reordenable").sortable({
                stop: async function(e, ui)
                {
                    await actualizarOrdenes();
                }
            });

            async function actualizarOrdenes() {
                const ids = obtenerIdsDeElementos();
                await enviarIdsAlBackend(ids);
            }

            function obtenerIdsDeElementos(){
                const ids = $(".ids").map(function() {
                    return $(this).val();
                }).get();
                
                return ids;
            }
            async function enviarIdsAlBackend(ids){
                var data = JSON.stringify(ids);
                await fetch(urlOrdenar, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
            }
        })
    </script>
}